#!/usr/bin/env zsh

#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# XDG -hao

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

if [[ -d ~/.local/bin ]]; then
  path=("$HOME/.local/bin" $path)
fi

if [[ -d ~/.cargo/bin ]]; then
  path=("$HOME/.cargo/bin" $path)
fi

if [[ -d ~/gopath ]]; then
  export GOROOT=/usr/local/opt/go/libexec
  export GOPATH=~/gopath
  path=($path "$GOROOT/bin" "$GOPATH/bin")
fi

path=($path "${XDG_CONFIG_HOME}/fzf/bin")

export HOMEBREW_NO_ANALYTICS=1
